//! User-provided Rust transform support.
//!
//! The user supplies the body of a function `fn transform(batch: RecordBatch)
//! -> Result<RecordBatch, String>`. Riffle injects this into a precompiled
//! cargo scaffold (one cdylib crate) under `~/.riffle/transform-scaffold/`,
//! runs `cargo build --release`, then dynamically loads the resulting library.
//!
//! Batches cross the FFI boundary as Arrow IPC stream bytes — slower than the
//! Arrow C Data Interface, but bulletproof and ABI-tolerant.

use anyhow::{anyhow, Context, Result};
use arrow::array::RecordBatch;
use arrow::ipc::reader::StreamReader;
use arrow::ipc::writer::StreamWriter;
use libloading::Library;
use std::io::Cursor;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;

const SCAFFOLD_VERSION: &str = "1";
const ARROW_VERSION: &str = "58";

/// Locate (or create) the scaffold workspace under the user's home directory.
fn scaffold_dir() -> Result<PathBuf> {
    let base = dirs::home_dir().ok_or_else(|| anyhow!("could not resolve home directory"))?;
    Ok(base.join(".riffle").join(format!("transform-scaffold-v{}", SCAFFOLD_VERSION)))
}

fn scaffold_workspace_cargo_toml() -> &'static str {
    r#"[workspace]
members = ["user_transform"]
resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
"#
}

fn scaffold_user_cargo_toml() -> String {
    format!(
        r#"[package]
name = "user_transform"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
arrow = "{arrow}"
"#,
        arrow = ARROW_VERSION,
    )
}

const TEMPLATE_LIB_RS: &str = r#"// Generated by Riffle. Do not edit by hand.
//
// User code is injected into `user_transform` below. The wrapper takes
// Arrow IPC stream bytes in, runs user code, and serialises the result back
// to Arrow IPC stream bytes.

use arrow::array::RecordBatch;
use arrow::ipc::reader::StreamReader;
use arrow::ipc::writer::StreamWriter;
use std::io::Cursor;

fn user_transform(batch: RecordBatch) -> Result<RecordBatch, String> {
    // ===== USER CODE =====
{{USER_CODE}}
    // ===== END USER CODE =====
}

unsafe fn write_buf(out_ptr: *mut *mut u8, out_len: *mut usize, bytes: Vec<u8>) {
    let mut boxed = bytes.into_boxed_slice();
    *out_ptr = boxed.as_mut_ptr();
    *out_len = boxed.len();
    std::mem::forget(boxed);
}

fn run(input: &[u8]) -> Result<Vec<u8>, String> {
    let mut reader = StreamReader::try_new(Cursor::new(input), None)
        .map_err(|e| format!("ipc read init: {e}"))?;
    let schema = reader.schema();
    let mut input_batches = Vec::new();
    while let Some(batch) = reader.next() {
        input_batches.push(batch.map_err(|e| format!("ipc read batch: {e}"))?);
    }
    let in_batch = if input_batches.is_empty() {
        RecordBatch::new_empty(schema)
    } else if input_batches.len() == 1 {
        input_batches.into_iter().next().unwrap()
    } else {
        arrow::compute::concat_batches(&schema, &input_batches)
            .map_err(|e| format!("concat batches: {e}"))?
    };

    let out = user_transform(in_batch)?;

    let mut buf: Vec<u8> = Vec::with_capacity(1024);
    {
        let mut w = StreamWriter::try_new(&mut buf, &out.schema())
            .map_err(|e| format!("ipc writer init: {e}"))?;
        w.write(&out).map_err(|e| format!("ipc write: {e}"))?;
        w.finish().map_err(|e| format!("ipc finish: {e}"))?;
    }
    Ok(buf)
}

/// Stable C ABI entry point.
///
/// On success: writes serialized output bytes to `*out_ptr` / `*out_len`,
/// returns 0. The caller must release the buffer via `riffle_free`.
///
/// On failure: writes a UTF-8 error message to `*err_ptr` / `*err_len` and
/// returns 1. The caller must release the error via `riffle_free`.
#[no_mangle]
pub unsafe extern "C" fn riffle_transform_v1(
    in_ptr: *const u8,
    in_len: usize,
    out_ptr: *mut *mut u8,
    out_len: *mut usize,
    err_ptr: *mut *mut u8,
    err_len: *mut usize,
) -> i32 {
    *out_ptr = std::ptr::null_mut();
    *out_len = 0;
    *err_ptr = std::ptr::null_mut();
    *err_len = 0;

    if in_ptr.is_null() {
        let msg = b"null input ptr".to_vec();
        write_buf(err_ptr, err_len, msg);
        return 1;
    }
    let input = std::slice::from_raw_parts(in_ptr, in_len);

    let result = std::panic::catch_unwind(|| run(input));
    match result {
        Ok(Ok(bytes)) => {
            write_buf(out_ptr, out_len, bytes);
            0
        }
        Ok(Err(msg)) => {
            write_buf(err_ptr, err_len, msg.into_bytes());
            1
        }
        Err(_) => {
            write_buf(err_ptr, err_len, b"user transform panicked".to_vec());
            1
        }
    }
}

/// Free a buffer returned by `riffle_transform_v1`.
#[no_mangle]
pub unsafe extern "C" fn riffle_free(ptr: *mut u8, len: usize) {
    if ptr.is_null() || len == 0 {
        return;
    }
    let _ = Vec::from_raw_parts(ptr, len, len);
}
"#;

fn ensure_scaffold(root: &Path) -> Result<()> {
    let user_dir = root.join("user_transform").join("src");
    std::fs::create_dir_all(&user_dir).context("create user_transform/src")?;

    let ws_toml = root.join("Cargo.toml");
    write_if_changed(&ws_toml, scaffold_workspace_cargo_toml())?;

    let user_toml = root.join("user_transform").join("Cargo.toml");
    write_if_changed(&user_toml, &scaffold_user_cargo_toml())?;

    // Note: lib.rs is rewritten on every compile to inject user code.
    Ok(())
}

fn write_if_changed(path: &Path, contents: &str) -> Result<()> {
    let needs_write = match std::fs::read_to_string(path) {
        Ok(existing) => existing != contents,
        Err(_) => true,
    };
    if needs_write {
        std::fs::write(path, contents)
            .with_context(|| format!("write {}", path.display()))?;
    }
    Ok(())
}

fn dylib_filename() -> &'static str {
    if cfg!(target_os = "windows") {
        "user_transform.dll"
    } else if cfg!(target_os = "macos") {
        "libuser_transform.dylib"
    } else {
        "libuser_transform.so"
    }
}

/// Compile result: either ok with library path, or err with stderr text.
pub struct CompileOk {
    pub dylib_path: PathBuf,
    pub stderr: String,
}

/// Compile a user-supplied transform body. Returns the path to the built
/// cdylib, or an `Err` containing rustc/cargo output on failure.
pub fn compile(user_code: &str) -> Result<CompileOk, String> {
    let root = scaffold_dir().map_err(|e| format!("{e}"))?;
    ensure_scaffold(&root).map_err(|e| format!("{e}"))?;

    let lib_rs = root.join("user_transform").join("src").join("lib.rs");
    let injected = TEMPLATE_LIB_RS.replace("{{USER_CODE}}", user_code);
    write_if_changed(&lib_rs, &injected).map_err(|e| format!("write lib.rs: {e}"))?;

    let output = Command::new("cargo")
        .args(["build", "--release", "-p", "user_transform"])
        .current_dir(&root)
        .output()
        .map_err(|e| format!("failed to invoke cargo (is it on PATH?): {e}"))?;

    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    if !output.status.success() {
        return Err(stderr);
    }

    let dylib = root.join("target").join("release").join(dylib_filename());
    if !dylib.exists() {
        return Err(format!("cargo reported success but {} is missing", dylib.display()));
    }
    Ok(CompileOk { dylib_path: dylib, stderr })
}

type RiffleTransformV1 = unsafe extern "C" fn(
    *const u8,
    usize,
    *mut *mut u8,
    *mut usize,
    *mut *mut u8,
    *mut usize,
) -> i32;
type RiffleFree = unsafe extern "C" fn(*mut u8, usize);

/// Loaded transform library plus its entry points.
pub struct TransformLib {
    _lib: Library,
    transform: RiffleTransformV1,
    free: RiffleFree,
}

impl std::fmt::Debug for TransformLib {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TransformLib").finish_non_exhaustive()
    }
}

impl TransformLib {
    pub fn load(dylib: &Path) -> Result<Arc<Self>> {
        let lib = unsafe { Library::new(dylib) }
            .with_context(|| format!("dlopen {}", dylib.display()))?;
        let transform: RiffleTransformV1 = unsafe {
            *lib.get::<RiffleTransformV1>(b"riffle_transform_v1")
                .context("symbol riffle_transform_v1 not found")?
        };
        let free: RiffleFree = unsafe {
            *lib.get::<RiffleFree>(b"riffle_free")
                .context("symbol riffle_free not found")?
        };
        Ok(Arc::new(Self { _lib: lib, transform, free }))
    }

    /// Apply the user's transform to a single batch.
    pub fn apply(&self, batch: &RecordBatch) -> Result<RecordBatch> {
        // Encode input.
        let mut input_buf: Vec<u8> = Vec::with_capacity(1024);
        {
            let mut w = StreamWriter::try_new(&mut input_buf, &batch.schema())
                .context("ipc writer init")?;
            w.write(batch).context("ipc write")?;
            w.finish().context("ipc finish")?;
        }

        let mut out_ptr: *mut u8 = std::ptr::null_mut();
        let mut out_len: usize = 0;
        let mut err_ptr: *mut u8 = std::ptr::null_mut();
        let mut err_len: usize = 0;

        let rc = unsafe {
            (self.transform)(
                input_buf.as_ptr(),
                input_buf.len(),
                &mut out_ptr,
                &mut out_len,
                &mut err_ptr,
                &mut err_len,
            )
        };

        if rc != 0 {
            let msg = unsafe {
                if err_ptr.is_null() || err_len == 0 {
                    "user transform failed (no error message)".to_string()
                } else {
                    let slice = std::slice::from_raw_parts(err_ptr, err_len);
                    String::from_utf8_lossy(slice).into_owned()
                }
            };
            unsafe { (self.free)(err_ptr, err_len) };
            return Err(anyhow!("user transform error: {}", msg));
        }

        let bytes = unsafe { std::slice::from_raw_parts(out_ptr, out_len).to_vec() };
        unsafe { (self.free)(out_ptr, out_len) };

        let mut reader = StreamReader::try_new(Cursor::new(bytes), None)
            .context("ipc read init")?;
        let mut batches = Vec::new();
        while let Some(b) = reader.next() {
            batches.push(b.context("ipc read batch")?);
        }
        if batches.is_empty() {
            // Empty result is allowed: build an empty batch using the writer's schema.
            let schema = reader.schema();
            return Ok(RecordBatch::new_empty(schema));
        }
        if batches.len() == 1 {
            return Ok(batches.into_iter().next().unwrap());
        }
        let schema = batches[0].schema();
        Ok(arrow::compute::concat_batches(&schema, &batches).context("concat batches")?)
    }
}

/// Compile + load convenience helper.
pub fn compile_and_load(user_code: &str) -> Result<Arc<TransformLib>> {
    match compile(user_code) {
        Ok(ok) => TransformLib::load(&ok.dylib_path),
        Err(stderr) => Err(anyhow!("rust transform compile failed:\n{}", stderr)),
    }
}
